# Generated by Django 3.0.7 on 2020-07-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200702_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='main_product/default.jpg', upload_to='main_product/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='main_product/default.jpg', upload_to='main_product/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='main_product/default.jpg', upload_to='main_product/'),
        ),
    ]
