# Generated by Django 3.0.8 on 2021-04-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20210429_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
