# Generated by Django 3.2.10 on 2022-04-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220424_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField(max_length=254)),
                ('facebook', models.URLField(max_length=254)),
                ('twitter', models.URLField(max_length=254)),
                ('WhatsApp', models.URLField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='Phone',
            field=models.CharField(default=1, max_length=22),
            preserve_default=False,
        ),
    ]
