# Generated by Django 3.0.8 on 2022-08-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220810_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='main_product'),
        ),
        migrations.AddField(
            model_name='info',
            name='pinterest',
            field=models.URLField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='tripadvisor',
            field=models.URLField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='viator',
            field=models.URLField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
