# Generated by Django 3.0.8 on 2022-08-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20220810_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to='main_product'),
        ),
    ]
