# Generated by Django 3.2.10 on 2022-04-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='Pricess',
        ),
        migrations.AddField(
            model_name='pricess',
            name='Tours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Tours_Pricess', to='Tours.tours'),
            preserve_default=False,
        ),
    ]
