# Generated by Django 3.2.10 on 2022-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0002_auto_20220414_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursbook',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
