# Generated by Django 3.2.10 on 2022-04-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_auto_20220415_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='pricee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
