# Generated by Django 3.2.10 on 2022-04-27 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tours', '0004_auto_20220415_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Important_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharitableGivin', models.TextField()),
                ('TourandPrices', models.TextField()),
                ('ChildrenPolicy', models.TextField()),
                ('DepositandPayment', models.TextField()),
                ('TourVoucher', models.TextField()),
                ('CancellationPolicy', models.TextField()),
                ('EmergencyCancellationPolicy', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
