# Generated by Django 3.2.10 on 2022-04-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0005_important_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='featureTours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Tours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tours.tours')),
            ],
        ),
    ]
