# Generated by Django 3.0.8 on 2022-08-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0008_auto_20220810_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursbook',
            name='children',
            field=models.CharField(choices=[(' 1 ', '1 '), ('2 ', '2'), ('3', '3'), ('4', '4')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
