# Generated by Django 3.0.8 on 2022-08-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0009_toursbook_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toursbook',
            name='adults',
            field=models.CharField(choices=[(' 1 ', '1 '), ('2 ', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=100),
        ),
        migrations.AlterField(
            model_name='toursbook',
            name='children',
            field=models.CharField(choices=[(' 1 ', '1 '), ('2 ', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=100),
        ),
    ]
