# Generated by Django 3.0.8 on 2021-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'أعداد المجلة  '},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-title',), 'verbose_name': 'مجلة'},
        ),
        migrations.RemoveField(
            model_name='story',
            name='footer',
        ),
        migrations.AddField(
            model_name='story',
            name='Authorpdf',
            field=models.FileField(default=1, upload_to='main_tour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='الاسم الكامل :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='أعداد المجلة :'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200, verbose_name='اسم البحث :'),
        ),
    ]
