# Generated by Django 3.0.8 on 2021-07-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210724_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name_plural': 'أعداد المجلة  '},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-title',), 'verbose_name_plural': 'مجلة'},
        ),
    ]
