# Generated by Django 3.0.8 on 2021-03-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title3', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_product')),
            ],
        ),
    ]
