# Generated by Django 3.0.8 on 2021-03-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='about',
        ),
    ]
