# Generated by Django 3.0.8 on 2021-05-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_our_values2'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_Text', models.TextField(max_length=1000)),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to='main_product')),
            ],
        ),
    ]
