# Generated by Django 3.0.8 on 2021-10-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='Privacy_Text2',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
