# Generated by Django 3.2.10 on 2022-04-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_privacy_privacy_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Our_Story',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Our_Values',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Our_Values2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Our_image',
        ),
        migrations.AddField(
            model_name='about',
            name='video',
            field=models.URLField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='Who_We_Are',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
